disabled_rules:
- identifier_name
opt_in_rules:
- empty_count
- empty_string
- vertical_whitespace_between_cases
- yoda_condition
- multiline_parameters
- multiline_parameters_brackets
- multiline_literal_brackets
- multiline_arguments_brackets
- multiline_arguments
- local_doc_comment
- missing_docs
- force_unwrapping
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 20
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
